name: Build patched parted .deb

on: push

jobs:
  build-deb:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential devscripts debhelper fakeroot \
            libdevmapper-dev libglib2.0-dev libreadline-dev libsigc++-2.0-dev \
            libuuid1 uuid-dev pkg-config python3-all python3-pip python3-setuptools \
            python3-wheel texinfo rsync gperf checkinstall

      - name: Download GNU parted
        run: |
          wget https://ftp.gnu.org/gnu/parted/parted-3.6.tar.xz
          tar -xvf parted-3.6.tar.xz

      - name: Apply patch
        working-directory: parted-3.6
        run: |
          cp ../3.6.patch .
          patch -p0 < 3.6.patch

      - name: Configure & build
        working-directory: parted-3.6
        run: |
          ./configure --prefix=/usr --disable-static
          make -j$(nproc)

      - name: Run tests
        working-directory: parted-3.6
        run: sudo make check

      - name: Package .deb
        working-directory: parted-3.6
        run: |
          sudo checkinstall --pkgname=parted-patched \
                            --pkgversion=$(date +%Y%m%d%H%M)-patched \
                            --backup=no \
                            --deldoc=yes \
                            --default \
                            --install=no

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: parted-patched-deb
          path: parted-3.6/*.deb

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: "parted-3.6/*.deb"
